# app/ui/components/output_analysis.py

import gradio as gr

# Responsibility: display the analysis generated by analyzer_node
def create_output_analysis():
    analysis_output = gr.Textbox(
        label="analysis_output",  # No internal label - using external section title with icon
        value="",  # Explicit empty string instead of None
        placeholder="Analysis will appear here",
        interactive=False,
        lines=20,  # Increased lines for better readability
        max_lines=30,  # Allow expansion up to 30 lines
        show_label=False
    )
    return analysis_output
