# app/ui/components/output_plan.py

import gradio as gr

# Responsibility: display the plan generated by planner_node
def create_output_plan():
    plan_output = gr.Textbox(
        label="plan_output",  # No internal label - using external section title with icon
        value="",  # Explicit empty string instead of None
        placeholder="Plan will appear here",
        interactive=False,
        lines=20,  # Increased lines for better readability
        max_lines=30,  # Allow expansion up to 30 lines
        show_label=False
    )
    return plan_output
