# app/constants.py

SIMILARITY_THRESHOLD = 0.60
HISTORICAL_TOP_K = 5

DEFAULT_CONFIDENCE_NO_HISTORY = 0.75
DEFAULT_CONFIDENCE_WITH_HISTORY = 0.70

DEFAULT_CONFIDENCE_BASE = 0.75

# Token budget management
PUBLIC_DEMO_SESSION_ID = "public-demo"
MAX_TOKENS = 1000 
MAX_ATTEMPTS = 2
TEMPERATURE = 0.2
DAILY_LIMIT = 400000
SESSION_LIMIT = 8000