# /app/graph/state.py
# This file contains the state definition for the decision support agent.

from typing import Annotated, List
from typing_extensions import TypedDict

from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage


# DecisionState includes all necessary fields for the agent.
#
# IMPORTANT SEMANTIC RULES:
# - `messages` represents the USER ↔ ASSISTANT conversational history ONLY
# - `messages` MUST be written exclusively by the FINAL response node
# - Technical nodes (retriever, rag, planner, analyzer) MUST NOT write messages
# - `add_messages` reducer ensures automatic accumulation across turns
#
class DecisionState(TypedDict):
    # ------------------------------------------------------------------
    # CHAT STATE (CONVERSATIONAL ONLY)
    # ------------------------------------------------------------------

    # Accumulated chat history (user + assistant messages only).
    # Managed via LangGraph `add_messages` reducer.
    messages: Annotated[List[BaseMessage], add_messages]

    # ------------------------------------------------------------------
    # USER INPUT
    # ------------------------------------------------------------------

    # Current user question
    question: str

    # ------------------------------------------------------------------
    # PLANNING / REASONING
    # ------------------------------------------------------------------

    # Step-by-step plan generated by planner_node
    plan: str | None

    # Documents retrieved by retriever_node (supportive evidence only)
    retrieved_docs: List[str]

    # Analytical reasoning (pros / cons / trade-offs)
    analysis: str | None

    # ------------------------------------------------------------------
    # DECISION OUTPUT
    # ------------------------------------------------------------------

    # Final decision text generated by decision_node
    decision: str | None

    # Confidence score for the decision (0.0 – 1.0)
    confidence: float | None

    # Flag indicating that the decision is final and should not be recomputed
    decision_finalized: bool

    # Retry attempts counter (for intelligent routing / fallback)
    attempts: int

    # ------------------------------------------------------------------
    # RAG (AUTHORITATIVE CONTEXT)
    # ------------------------------------------------------------------

    # Raw context documents uploaded by the user (full text)
    context_docs: List[str]

    # Formatted RAG context string injected into the LLM prompt
    rag_context: str | None

    # ------------------------------------------------------------------
    # REPORTING / UI
    # ------------------------------------------------------------------

    # Full HTML report of the decision session
    report_html: str | None

    # HTML preview snippet for Gradio UI (no <html>/<body> wrapper)
    report_preview: str | None

