# /app/graph/state.py
# This file contains the state definition for the decision support agent.

from typing import Annotated
from typing_extensions import TypedDict
from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage

# DecisionState includes all necessary fields for the agent
# The 'messages' field uses add_messages reducer for proper message handling
class DecisionState(TypedDict):
    # Chat messages history with add_messages reducer
    messages: Annotated[list[BaseMessage], add_messages]

    # User's input question
    question: str

    # Step-by-step plan generated by planner_node
    plan: str | None

    # List of documents retrieved by retriever_node
    retrieved_docs: list[str]

    # Analysis summary of options/pros/cons
    analysis: str | None

    # Final decision generated by decision_node
    decision: str | None

    # Confidence score of the decision (0 to 1)
    confidence: float | None

    # Retry attempts counter (for intelligent routing)
    attempts: int
    
    # HTML report of the session (generated by summarize node)
    report_html: str | None
    
    # HTML preview for Gradio UI (without html/head/body wrapper)
    report_preview: str | None

    # 🆕 Hybrid RAG fields
    # Documents of context uploaded by the user for RAG support
    context_docs: list[str]  # Raw uploaded document texts
    
    # RAG context string generated by rag_node (retrieved chunks)
    rag_context: str | None  # Formatted context for LLM injection
    
    # 🆕 Decision finalization flag (prevents unnecessary re-decisions)
    decision_finalized: bool  # True when decision is final and stable
